## 1 Time-Varying Data

The goal of this exercise is to introduce students to using Python to manipulate and visualize time-varying data. We'll use an auditory neurophysiology experiment to illustrate the key concepts. In this experiment, recordings of bird songs are presented to an animal while we record from neurons in the auditory system.

![experiment diagram](images/experiment_diagram.png "Title")

Some of the cells are left blank or have placeholder text. Your assignment is to complete those cells. Download the notebook as an 'ipynb' file (see the `File/Download as` menu) and submit this for grading.

### 1A Introduction to Python Notebooks

Welcome! This web page is a Python notebook. It's a interactive document that lets you mix text and computer code, organized into `cells`. A cell can contain either text or code. This is a text cell. You can edit the contents of this cell by double-clicking, then save by typing `Ctrl-Enter`.

The cell below this is a code cell, as indicated by `In [ ]:` off to the left. When you type `Ctrl-Enter` in a code cell, the contents are passed to the Python interpreter. Each line is evaluated in turn. If the last line generates some output, this will be shown below the code cell. To run the notebook, you need to type `Ctrl-Enter` in each cell (including the one below):

In [2]:
# Python comments are marked by `#`

# These lines of code import some external libraries we'll use in this exercise:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

# This is a Python string literal. It will evaluate to itself.
"Hello world"

'Hello world'

Take a look at the menus and buttons above. You can cut and paste cells with the `Edit` menu to move them around. You can execute one or more cells using the `Cell` menu. The Python interpreter is called a `kernel`. Under the `Kernel` menu, you can restart or interrupt the interpreter if it gets stuck. The `Help` menu explains more about using the notebook and has links to some of the main scientific programming libraries.

If you're completely new to programming or to Python, you should go through the following exercises from [Software Carpentry](https://software-carpentry.org/). This should take you about 60-90 minutes. You can create new notebooks under `File/New Notebook` to work through them, or you can insert cells here.

- [Running and Quitting Python](http://swcarpentry.github.io/python-novice-gapminder/01-run-quit/)
- [Variables](http://swcarpentry.github.io/python-novice-gapminder/02-variables/)
- [Data Types](http://swcarpentry.github.io/python-novice-gapminder/03-types-conversion/)
- [Functions](http://swcarpentry.github.io/python-novice-gapminder/04-built-in/)
- [Lists](http://swcarpentry.github.io/python-novice-gapminder/11-lists/)
- [Loops](http://swcarpentry.github.io/python-novice-gapminder/12-for-loops/)

---
### 1B Working with Time Series and Point Process Data

In neuroscience, much of the data we'll be working with is a representation of some process that changes in time. There are two fundamental ways of representing time-varying data in a computer:

- A **time series** is a quantitative physical property of a system measured over a time interval. In digital computers, time series data are always sampled at discrete moments in time, usually at fixed intervals. The *sampling rate* of the data is the number of times per second the underlying process was measured. Examples of time series include sound waveforms and recordings of extracellular voltage.

- A **point process** is a series of times when an event took place. An example of a point process is the set of times when a neuron produced an action potential (spike).

Both point processes and time series are represented in Python in data structures called an `arrays`. We'll use a library called [numpy](http://www.numpy.org/) to store and manipulate arrays. Note that in the first code cell above, we imported the numpy library and gave it the alias `np`, so all the calls to numpy functions will be preceded by `np.`

Here's an example of creating an array:

In [3]:
arr = np.array([1.0, 1.2, 0.8, 1.0])

As with lists, we can access specific elements or ranges of elements using indices:

In [4]:
arr[0]

1.0

In [5]:
arr[2:]

array([0.8, 1. ])

You can do math operations on every element of the array with a single function call:

In [6]:
np.sin(arr)

array([0.84147098, 0.93203909, 0.71735609, 0.84147098])

You can add a scalar to an array, or add two arrays of the same size.

In [7]:
56 + arr

array([57. , 57.2, 56.8, 57. ])

In [8]:
arr + (2 * arr)

array([3. , 3.6, 2.4, 3. ])

---
## 1C Working with Acoustic Stimuli

Sound consists of waves of pressure moving through the air or another medium. When these waves press against the eardrum, the bones (or bone, if you're a bird) in the middle ear transmit the wave to the fluid in the cochlea. Movements in this fluid are detected by hair cells, which transduce the sound into neural signals. Sound is recorded with a microphone, which transduces pressure changes into electrical voltage changes. These in turn can be sampled by a digitizer and turned into an array of numbers.

Sound recordings can be stored in a variety of file formats. One of the most common is the `wave` format, which is what we'll be using here. The stimulus files used in this experiment have been placed in the `stimuli` directory. We can use the `os` module in Python to list the contents of this directory:

In [9]:
import os
os.listdir('stimuli')

['motifs.csv',
 'A2.wav',
 'A0.wav',
 'C8.wav',
 'B8.wav',
 'A6.wav',
 'C2.wav',
 'B6.wav',
 'A8.wav',
 'C0.wav',
 'B0.wav',
 'B2.wav',
 'C6.wav']

Let's see what the contents of `A0.wav` look like. We'll use a python package called `ewave` to load the file. The `ewave.open` function returns an object that we can use to access the data.

In [10]:
import ewave
wavfile = ewave.open("stimuli/A0.wav")
wavfile

<open ewave.wavfile 'b'stimuli/A0.wav'', mode 'r', dtype 'int16', sampling rate 20000 at 0x10d4b8908>

An important quantity to note is the **sampling rate**, which indicates how frequently the sound pressure wave was measured during the recording. 